# Generated by Django 5.2.4 on 2025-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
    ]
