# Generated by Django 5.2.4 on 2025-08-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_recipe', '0008_alter_ingredient_recipe_alter_instruction_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
